---

- name: Reset Git Environment
  hosts: test-servers
  gather_facts: no
  become: yes
  become_user: root
  vars:
    - HOSTNAME: "AWS-TEST-SERVER"
    - usr_for_git: "git"
    - usr_pwd_for_git: "pas2Wang"
    - global_git_usr: "deanwang"
    - global_git_usr_email: "wzq@systec.com.cn"
    - gitosis_dir_nm: "gitosis"
  tasks:
    - name: Remove Default Packages
      apt: pkg={{item}} state=absent
      with_items:
        - id-utils
        - python-setuptools
        
    - name: Remove Git Packages
      apt: pkg={{item}} state=absent
      with_items:
        - git-core
        - git-daemon-run

    - name: Remove Gollum(Git Wiki)
      gem: name=gollum state=absent
        
    - name: Remove necessary packages for Gollum
      apt: pkg={{item}} state=absent
      with_items:
        - apache2
        - ruby
        - ruby-dev
        - make
        - build-essential
        - libiconv*
        - libicu-dev
        - zlib1g-dev
      
    - name: Remove User of Git
      user: name={{usr_for_git}} remove=yes state=absent
    - group: name={{usr_for_git}} state=absent
    

