---

- name: Run Gollum
  hosts: test-servers
  gather_facts: no
  sudo: yes
#  ignore_errors: True
  vars:
    - HOSTNAME: "AWS-TEST-SERVER"
    - usr_for_git: "git"
    - usr_pwd_for_git: "pas2Wang"
    - global_git_usr: "deanwang"
    - global_git_usr_email: "wzq@systec.com.cn"
    - gitosis_dir_nm: "gitosis"
    - git_repo_root: "repositories"
    - gollum_repo_nm: "gollum-wiki.git"
  tasks:
    - name: Running Gollum Wiki Repository
      tags: gollum
      command: gollum chdir=/home/{{usr_for_git}}/{{git_repo_root}}/{{gollum_repo_nm}}
      register: output
    - debug: msg={{output.stdout}}
      tags: gollum