---

- name: Control Node Prepare
  hosts: localhost
  gather_facts: no
  tags: prepare
  roles:
  - general-prepare
  - distribute-ssh-keys




- name: Test Tasks
  hosts: remote-hosts
  gather_facts: yes
  tags: test
  tasks:
  - name: Debug Vars
    debug: msg=ansible_os_family={{ansible_os_family}}
  roles:
  - {role: ubuntu, when: ansible_os_family == 'Debian' }



