---

- set_fact: current_name="{{item}}"
- debug: msg=current_name={{current_name}}
- name: Creates mail.yml in roles every sub-directory
  file: path="{{root_path}}/{{project_name}}/roles/{{current_name}}/{{item.key}}/{{item.value.file}}" state="touch"
  with_dict: "{{role_subdir_files}}"