---

- set_fact: role_name="{{item}}"
- name: Creates mail.yml in roles every sub-directory
  file: path="{{root_path}}/{{project_name}}/roles/{{role_name}}/{{item.key}}/{{item.value.file}}" state="touch"
  with_dict: "{{role_subdir_files}}"