---

# from vars folder
- include_vars: vars/other.yml
# from default folder
- include_vars: defaults/another.yml 

- name: Task Debug OS Role Vars
  debug: msg="os_version={{os_version}}"
- debug: msg=os_alias={{os_alias}}
- name: OS Role Default Vars
  debug: msg=os_type={{os_type}}
- debug: msg=os_dist={{os_dist}}
- debug: msg=os_bit={{os_bit}}
- name: template configuration file
  template: src=default.j2 dest=~/foo.conf
  notify:
     - playbook end
- name: command executed
  command: ls
  notify:
     - playbook executed some commands