---

include_vars:
- user_define.yml
- script_define.yml

- name: Reset Ansible_Project Running Result
  hosts: localhost
  gather_facts: no
  tags: 'remove project'
  tasks:
    - name: Remove project folder
      file: path="{{root_path}}{{project_name}}" state=absent

  