---

- name: Edit Network Interface Config File
  sudo: yes
  lineinfile:
    dest=/etc/network/interfaces
    backup=yes
    create=yes
    state="{{item.state}}"
    regexp="^(auto {{net_int_params.key}}).*\n\r(.+\n\r)\n\r$"
    line="{{item.line}}"
  with_items:
  - {state: 'present', line: "#\1
  \n\riface {{net_int_params.key}} inet manual
  \n\r    up ip link set dev $IFACE up
  \n\r    down ip link set dev $IFACE down"}
#    notify:
#      - Restart Network Service