---

- name: Edit Network Interface Config File
  sudo: yes
  lineinfile:
    dest=/etc/network/interfaces
    backup=yes
    create=yes
    state="{{item.state}}"
    regexp="^(auto {{net_int_params.key}}).*\n\r(.+\n\r)\n\r$"
    line="{{item.line}}"
  with_items:
  - {state: 'present', line: "#\1
  \n\riface {{net_int_params.key}} inet {{net_int_params.value.mode}}
  \n\r    address {{net_int_params.value.ip}}
  \n\r    mask {{net_int_params.value.mask}}
  \n\r    gateway {{net_int_params.value.gateway}}"}
#    notify:
#      - Restart Network Service

